name: Build EXE

on:
  push:
    branches: [ finish ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r install.txt  # Uncomment if you have dependencies
    - name: Build EXE
      run: pyinstaller --onefile projekt.py
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-exe
        path: dist/*.exe
